### ISSUE TITLE
Backend controller infinite loop Magento 2.3

### ISSUE THREAD

**Issue by pixiemediaweb** [UltimateModuleCreator/umc#18] opened 2019-03-20 11:24 UTC
When creating entities and linking them from the admin menu, if you select one in 2.3.x you get sent in a loop of;

[url]/[adminpath]/[module_name]/[enttiy_name]/index/key/48484848484/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/dashboard

**Comment by sidealice** [comment] 2019-03-20 18:54
same issue.

**Comment by sidealice** [comment] 2019-03-26 07:18
any good news for this issue?

**Comment by Azaciux** [comment] 2019-04-04 16:14
This appears to be caused by secret keys being added to the URLs.

https://github.com/magento/magento2/issues/21454

However, the issue is that the module creating is coming up with a 404, so there is a problem that still needs resolving :)

**Comment by Azaciux** [comment] 2019-04-04 16:23
On closer inspection, changing the route ID seems to fix the 404 for me. So i'm guessing there's an issue with the way it's being generated. My module vendor contained many capitals I.E "ThisIsMyVendor". 

Which seem to output the route to "this_is_my_vendor", altering the route file has resolved this.

**Comment by sidealice** [comment] 2019-04-16 15:26
i have to fix it manually.  rename "ThisIsMyVendor"  or "ThisIsMyModule"  to other name

How to auto fix this issue? what about to replace "ThisIsMyVendor" to "vendor" and  "ThisIsMyModule" to "module"? 
or How about to add a field for naming by pre-defined?

**Comment by UltimateModuleCreator** [comment] 2019-05-10 12:19
@Azaciux @sidealice can you please send me a faulty module configuration file so I can reproduce it and fix it? You can find the file in `var/umc` and should have the same name as the module itself. Send it at ultimate.module.creator@gmail.com

**Comment by UltimateModuleCreator** [comment] 2020-06-26 12:56
This should be fixed in 4.0.0

**Closed as completed by UltimateModuleCreator** 2020-06-26 12:56 UTC
Labels: bug, magento-2.3, in-generated-code
